# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='question',
            field=models.CharField(choices=[('kek', 'kek'), ('lol', 'lol'), ('heh', 'heh'), ('lmao', 'lmao')], default='kek', max_length=4),
        ),
    ]
